# Generated by Django 4.2.5 on 2023-09-26 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NeonLights',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='inventory_images')),
                ('name', models.CharField(max_length=255)),
                ('inches', models.CharField(max_length=255)),
                ('ip_rating', models.CharField(blank=True, max_length=150, null=True)),
                ('led_lights_used', models.IntegerField(blank=True, null=True)),
                ('sheet_mm', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neon_lights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Neon Lights',
                'ordering': ('name',),
            },
        ),
    ]
