# Generated by Django 4.2.5 on 2023-10-25 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(editable=False, max_length=36, primary_key=True, serialize=False)),
                ('product_name', models.CharField(editable=False, max_length=255)),
                ('price', models.FloatField(blank=True, null=True)),
                ('product_image_path', models.CharField(editable=False, max_length=255)),
                ('username', models.CharField(editable=False, max_length=150)),
                ('email', models.EmailField(editable=False, max_length=254)),
                ('phone_number', models.CharField(editable=False, max_length=15)),
                ('status', models.CharField(choices=[('NA', 'Not accepted'), ('IP', 'In progress'), ('CO', 'Complete')], default='NA', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='NeonLights',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='inventory_images')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField(blank=True, null=True)),
                ('inches', models.CharField(max_length=255)),
                ('ip_rating', models.CharField(blank=True, max_length=150, null=True)),
                ('led_lights_used', models.IntegerField(blank=True, null=True)),
                ('sheet_mm', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neon_lights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Neon Lights',
                'ordering': ('name',),
            },
        ),
    ]
