# Generated by Django 4.2.4 on 2023-09-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_neonlights_ip_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neonlights',
            name='meters',
        ),
        migrations.AddField(
            model_name='neonlights',
            name='led_lights_used',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neonlights',
            name='sheet_mm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
